version: '3.7'

volumes:
    logs:
        driver: local

services:
    php:
        image: php:7-alpine
        command: php -S 0.0.0.0:8080
    db:
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: hellokant
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        volumes:
          - ./article.sql:/docker-entrypoint-initdb.d/article.sql
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8100:80
        environment:
            - PMA_ARBITRARY=1
    composer:
        image: composer
        volumes: 
            - .:/var/www
        working_dir: /var/www


