version: '3.7'

services:
  iut_orm:
    container_name: iut_orm
    image: php:7-alpine
    env_file: ./config/db.conf.ini
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 3333:3000
    build:
        context: .
        dockerfile: ./dockerfile
    command: php -S 0.0.0.0:3000
    depends_on:
      - iut_db_orm
    links:
      - iut_db_orm
    networks:
      - orm

  iut_adminer_orm:
    container_name: iut_adminer_orm
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - iut_db_orm
    networks:
      - orm

  iut_db_orm:
    container_name: iut_db_orm
    image: mysql:latest
    env_file: ./config/db.conf.ini
    volumes:
      - ./db:/var/lib/mysql
      - ./article.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - orm

  composer:
    container_name: iut_composer_orm
    image: composer
    volumes: 
        - .:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - orm

networks:
  orm:
    driver: bridge